// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnFDjg1nAP0Ss7q7sj7nEEuPf1WgfEotY',
    appId: '1:836617178098:web:7b79a7e2a502f522ae796b',
    messagingSenderId: '836617178098',
    projectId: 'libsk-b68f5',
    authDomain: 'libsk-b68f5.firebaseapp.com',
    storageBucket: 'libsk-b68f5.firebasestorage.app',
    measurementId: 'G-FT0TRQVGJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1EttMUYmap8fOc0ck6cfpSLwPYY4ZAvY',
    appId: '1:836617178098:android:dc98f6a95f608bd0ae796b',
    messagingSenderId: '836617178098',
    projectId: 'libsk-b68f5',
    storageBucket: 'libsk-b68f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM7g6wVW7OO1KRG-zBvbYMTrxnmDikpE8',
    appId: '1:836617178098:ios:5fe430a583f5e75dae796b',
    messagingSenderId: '836617178098',
    projectId: 'libsk-b68f5',
    storageBucket: 'libsk-b68f5.firebasestorage.app',
    iosBundleId: 'com.example.libsk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM7g6wVW7OO1KRG-zBvbYMTrxnmDikpE8',
    appId: '1:836617178098:ios:5fe430a583f5e75dae796b',
    messagingSenderId: '836617178098',
    projectId: 'libsk-b68f5',
    storageBucket: 'libsk-b68f5.firebasestorage.app',
    iosBundleId: 'com.example.libsk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnFDjg1nAP0Ss7q7sj7nEEuPf1WgfEotY',
    appId: '1:836617178098:web:fbd7ed445b9c45eaae796b',
    messagingSenderId: '836617178098',
    projectId: 'libsk-b68f5',
    authDomain: 'libsk-b68f5.firebaseapp.com',
    storageBucket: 'libsk-b68f5.firebasestorage.app',
    measurementId: 'G-LV39LCHE0G',
  );
}
